/**
 * MVP data source: the fake JSON from the contract (`shared/schema/examples`).
 * Once the real parser exists, only this module changes (e.g. fetching a
 * file generated by the CLI) — the rest of the app stays intact.
 */

import rawProject from '../../../../shared/schema/examples/audio-recorder.json';
import { parseProjectJson } from '../schema/parserJson';
import { fromParserJson } from '../domain/fromParserJson';
import type { DomainProject } from '../domain/types';

export function loadProject(): DomainProject {
  return fromParserJson(parseProjectJson(rawProject));
}
