/**
 * Data source: a model generated by the CLI when available, otherwise the
 * bundled example from the contract (`shared/schema/examples`).
 *
 * Generate a real model with:
 *   crux-analyzer generate --src <crate>/src --out apps/web/public/model.json
 *
 * This is the only module that knows where the JSON comes from — the rest of
 * the app always receives a DomainProject.
 */

import bundledExample from '../../../../shared/schema/examples/audio-recorder.json';
import { parseProjectJson } from '../schema/parserJson';
import { fromParserJson } from '../domain/fromParserJson';
import type { DomainProject } from '../domain/types';

// Relative to the app's base (Vite's `BASE_URL`, always slash-terminated), so
// a static site served from a subpath fetches its own model instead of the
// domain root's. `/` in dev and in a default build.
const GENERATED_MODEL_URL = `${import.meta.env.BASE_URL}model.json`;

// A host embedding the built bundle — the VS Code extension's webview — has
// no HTTP origin to serve model.json from, so it injects the model as a
// global before the bundle boots. This is the embedding contract: injection
// outranks fetching, and an invalid injection falls through the same ladder
// as a stale artifact.
declare global {
  interface Window {
    __CRUX_MODEL__?: unknown;
  }
}

export async function loadProject(): Promise<DomainProject> {
  const injected = typeof window !== 'undefined' ? window.__CRUX_MODEL__ : undefined;
  if (injected !== undefined) {
    try {
      return fromParserJson(parseProjectJson(injected));
    } catch (error) {
      console.warn('Ignoring invalid injected model:', error);
    }
  }
  const raw = await fetchGeneratedModel();
  if (raw !== null) {
    try {
      return fromParserJson(parseProjectJson(raw));
    } catch (error) {
      // A stale artifact (e.g. from an older schema) must not break the app.
      console.warn('Ignoring invalid generated model, using bundled example:', error);
    }
  }
  return fromParserJson(parseProjectJson(bundledExample));
}

async function fetchGeneratedModel(): Promise<unknown | null> {
  try {
    const response = await fetch(GENERATED_MODEL_URL, {
      headers: { Accept: 'application/json' },
    });
    if (!response.ok) return null;
    // Vite's dev server answers unknown paths with index.html — only a JSON
    // content type counts as a generated model.
    if (!response.headers.get('content-type')?.includes('json')) return null;
    return await response.json();
  } catch {
    return null;
  }
}
