/**
 * Data source: a model generated by the CLI when available, otherwise the
 * bundled example from the contract (`shared/schema/examples`).
 *
 * Generate a real model with:
 *   crux-analyzer generate --src <crate>/src --out apps/web/public/model.json
 *
 * This is the only module that knows where the JSON comes from — the rest of
 * the app always receives a DomainProject.
 */

import bundledExample from '../../../../shared/schema/examples/audio-recorder.json';
import { parseProjectJson } from '../schema/parserJson';
import { fromParserJson } from '../domain/fromParserJson';
import type { DomainProject } from '../domain/types';

const GENERATED_MODEL_URL = '/model.json';

export async function loadProject(): Promise<DomainProject> {
  const raw = (await fetchGeneratedModel()) ?? bundledExample;
  return fromParserJson(parseProjectJson(raw));
}

async function fetchGeneratedModel(): Promise<unknown | null> {
  try {
    const response = await fetch(GENERATED_MODEL_URL, {
      headers: { Accept: 'application/json' },
    });
    if (!response.ok) return null;
    // Vite's dev server answers unknown paths with index.html — only a JSON
    // content type counts as a generated model.
    if (!response.headers.get('content-type')?.includes('json')) return null;
    return await response.json();
  } catch {
    return null;
  }
}
